name: fishpro
description: A comprehensive fishing tournament management application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  google_sign_in: ^6.1.6
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^12.1.1
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  sentry: ^7.12.0
  sentry_flutter: ^7.12.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.2.0
  firebase_analytics: ^10.0.0
  flutter_dotenv: ^5.0.2
  firebase_remote_config: ^4.4.7
  firebase_crashlytics: ^3.0.0
  connectivity_plus: ^3.0.0
  weather: ^2.0.0
  fl_chart: ^0.50.1
  provider: ^6.0.0
  vector_math: ^2.1.0
  sign_in_with_apple: ^4.0.0
  local_auth: ^2.1.0
  flutter_secure_storage: ^5.0.2
  otp: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
